export const products = [
  {
    id: 1,
    category: "pizzas",
    title: "Pizza Margherita",
    description: "Clásica napolitana con albahaca",
    price: 40.2,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697328636/margherita_uyo3yd.jpg",
    stock: 5,
  },
  {
    id: 2,
    category: "pizzas",
    title: "Pizza Pepperoni",
    description: "Deliciosa pizza con pepperoni y queso derretido",
    price: 45.5,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697328824/cebolla_bavoxd.webp",
    stock: 3,
  },
  {
    id: 3,
    category: "pizzas",
    title: "Pizza Vegetariana",
    description: "Pizza repleta de verduras frescas y queso",
    price: 42.0,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697328824/calabresa_xs6t2b.webp",
    stock: 6,
  },
  {
    id: 4,
    category: "pizzas",
    title: "Pizza BBQ",
    description: "Pizza con salsa barbacoa, pollo y cebolla roja",
    price: 48.8,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697328824/calabresa_xs6t2b.webp",
    stock: 7,
  },
  {
    id: 5,
    category: "pizzas",
    title: "Pizza Hawaiana",
    description: "Pizza con jamón, piña y queso derretido",
    price: 46.3,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697328636/margherita_uyo3yd.jpg",
    stock: 8,
  },
  {
    id: 6,
    category: "pizzas",
    title: "Pizza Cuatro Quesos",
    description: "Pizza con cuatro tipos diferentes de queso",
    price: 44.7,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697328636/margherita_uyo3yd.jpg",
    stock: 2,
  },
  {
    id: 7,
    category: "panes",
    title: "Pan Casero",
    description: "Pan recién horneado en casa",
    price: 5.0,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697329109/pan_h2msha.webp",
    stock: 3,
  },
  {
    id: 8,
    category: "panes",
    title: "Pan Brioche",
    description: "Pan dulce y suave estilo brioche",
    price: 6.5,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697329111/pan-brioche-sledibrioche_gaakxd.jpg",
    stock: 5,
  },
  {
    id: 9,
    category: "panes",
    title: "Baguette",
    description: "Pan francés estilo baguette",
    price: 3.5,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697329108/baguette-4-FP_vdxc0u.jpg",
    stock: 6,
  },
  {
    id: 10,
    category: "panes",
    title: "Pan Flauta",
    description: "Pan crujiente estilo flauta",
    price: 4.0,
    img: "https://res.cloudinary.com/dohsaecvv/image/upload/v1697329108/baguette-4-FP_vdxc0u.jpg",
    stock: 8,
  },
];
